### ISSUE TITLE
Draw Work Schedule Screen, Feedback and Reporting Screen (Guards) with desktop size (1440 x 2024) 

### ISSUE THREAD

**Issue by MockProject072024nhom6** [MockProject072024nhom6/MockProject_072024_Nhom6#28]
Deadline 10:00 PM 01/08/2024

**Comment by ndatn** [comment]
https://www.figma.com/design/HwDbuSUtttPSHDPcW18Zyp/Bodyguard-rental-website?node-id=1-2&t=YwlBEWKUCY5TkC1u-1
